"""Prototype macro knowledge base for the POC.

This file is intentionally separate from the management command so the seeded
knowledge can be reviewed, replaced, or promoted into a different knowledge
authoring workflow later.
"""

# Indicator definitions are broad and market-oriented rather than vendor-specific.
INDICATORS = [
    {
        "code": "CPI_YOY",
        "name": "Headline CPI YoY",
        "category": "inflation",
        "description": "Year-over-year headline consumer price inflation.",
        "frequency": "monthly",
        "source": "BLS / consensus macro data vendors",
        "unit": "percent",
        "rationale": "Headline CPI remains a core market anchor for inflation expectations and policy sensitivity.",
        "confidence_score": "0.92",
        "weight": "0.95",
        "lag_months": 1,
        "lag_notes": "Monthly release with moderate market lag into policy expectations.",
        "is_active": True,
    },
    {
        "code": "CORE_CPI_YOY",
        "name": "Core CPI YoY",
        "category": "inflation",
        "description": "Year-over-year CPI excluding food and energy.",
        "frequency": "monthly",
        "source": "BLS / consensus macro data vendors",
        "unit": "percent",
        "rationale": "Core CPI is widely used to gauge persistence in underlying inflation.",
        "confidence_score": "0.94",
        "weight": "1.00",
        "lag_months": 1,
        "lag_notes": "Often shapes policy narratives more than headline prints.",
        "is_active": True,
    },
    {
        "code": "CORE_PCE_YOY",
        "name": "Core PCE YoY",
        "category": "inflation",
        "description": "Year-over-year core personal consumption expenditures inflation.",
        "frequency": "monthly",
        "source": "BEA / consensus macro data vendors",
        "unit": "percent",
        "rationale": "Core PCE is the Fed's preferred inflation gauge and a key policy input.",
        "confidence_score": "0.96",
        "weight": "1.00",
        "lag_months": 1,
        "lag_notes": "Feeds directly into central-bank reaction function heuristics.",
        "is_active": True,
    },
    {
        "code": "UNEMP_RATE",
        "name": "Unemployment Rate",
        "category": "labor",
        "description": "Headline unemployment rate.",
        "frequency": "monthly",
        "source": "BLS / consensus macro data vendors",
        "unit": "percent",
        "rationale": "The unemployment rate is a high-signal labor slack measure for cycle assessment.",
        "confidence_score": "0.91",
        "weight": "0.92",
        "lag_months": 1,
        "lag_notes": "Labor indicators can lag turning points but still anchor policy interpretation.",
        "is_active": True,
    },
    {
        "code": "NFP_3M_AVG",
        "name": "Nonfarm Payrolls 3M Avg",
        "category": "labor",
        "description": "Three-month average of nonfarm payroll gains.",
        "frequency": "monthly",
        "source": "BLS / consensus macro data vendors",
        "unit": "thousands",
        "rationale": "A smoothed payroll trend is more useful than a single noisy monthly print.",
        "confidence_score": "0.88",
        "weight": "0.86",
        "lag_months": 1,
        "lag_notes": "Smoothing reduces noise but can delay inflection detection slightly.",
        "is_active": True,
    },
    {
        "code": "ISM_MFG_PMI",
        "name": "ISM Manufacturing PMI",
        "category": "growth",
        "description": "Purchasing managers' index for manufacturing activity.",
        "frequency": "monthly",
        "source": "ISM / consensus macro data vendors",
        "unit": "index",
        "rationale": "Manufacturing PMIs are timely directional reads on the industrial cycle.",
        "confidence_score": "0.87",
        "weight": "0.84",
        "lag_months": 0,
        "lag_notes": "Often leads harder activity data around turning points.",
        "is_active": True,
    },
    {
        "code": "ISM_SERVICES_PMI",
        "name": "ISM Services PMI",
        "category": "growth",
        "description": "Purchasing managers' index for services activity.",
        "frequency": "monthly",
        "source": "ISM / consensus macro data vendors",
        "unit": "index",
        "rationale": "Services activity matters heavily for broad growth and labor resilience.",
        "confidence_score": "0.87",
        "weight": "0.84",
        "lag_months": 0,
        "lag_notes": "Useful as a near-real-time gauge of domestic demand.",
        "is_active": True,
    },
    {
        "code": "UST2Y",
        "name": "US 2Y Treasury Yield",
        "category": "rates",
        "description": "Two-year US Treasury yield.",
        "frequency": "daily",
        "source": "Treasury market data",
        "unit": "percent",
        "rationale": "Front-end rates often encode policy expectations and repricing speed.",
        "confidence_score": "0.93",
        "weight": "0.93",
        "lag_months": 0,
        "lag_notes": "Market price reacts immediately to macro and policy surprises.",
        "is_active": True,
    },
    {
        "code": "UST10Y",
        "name": "US 10Y Treasury Yield",
        "category": "rates",
        "description": "Ten-year US Treasury yield.",
        "frequency": "daily",
        "source": "Treasury market data",
        "unit": "percent",
        "rationale": "The 10Y yield captures long-duration inflation and growth expectations.",
        "confidence_score": "0.93",
        "weight": "0.95",
        "lag_months": 0,
        "lag_notes": "Key benchmark for cross-asset discount-rate sensitivity.",
        "is_active": True,
    },
    {
        "code": "DXY",
        "name": "US Dollar Index",
        "category": "fx",
        "description": "Broad trade-weighted proxy for dollar strength.",
        "frequency": "daily",
        "source": "FX market data",
        "unit": "index",
        "rationale": "The dollar is a practical proxy for global liquidity and financial conditions.",
        "confidence_score": "0.89",
        "weight": "0.88",
        "lag_months": 0,
        "lag_notes": "Transmits quickly into EM and commodity conditions.",
        "is_active": True,
    },
    {
        "code": "BRENT",
        "name": "Brent Crude Oil",
        "category": "commodities",
        "description": "Front-month Brent crude oil price proxy.",
        "frequency": "daily",
        "source": "Commodity market data",
        "unit": "usd_per_barrel",
        "rationale": "Oil remains one of the fastest ways to express global growth and inflation impulses.",
        "confidence_score": "0.85",
        "weight": "0.82",
        "lag_months": 0,
        "lag_notes": "Commodity shocks can move inflation expectations immediately.",
        "is_active": True,
    },
    {
        "code": "COPPER_GOLD_RATIO",
        "name": "Copper Gold Ratio",
        "category": "cross_asset",
        "description": "Ratio of copper price to gold price as a cyclicality proxy.",
        "frequency": "daily",
        "source": "Commodity market data",
        "unit": "ratio",
        "rationale": "A higher copper-gold ratio often tracks stronger cyclical growth sentiment.",
        "confidence_score": "0.79",
        "weight": "0.75",
        "lag_months": 0,
        "lag_notes": "Useful as a market-led growth proxy rather than a hard macro series.",
        "is_active": True,
    },
    {
        "code": "IG_OAS",
        "name": "Investment Grade OAS",
        "category": "credit",
        "description": "Investment-grade option-adjusted spread.",
        "frequency": "daily",
        "source": "Credit market data",
        "unit": "basis_points",
        "rationale": "IG spreads summarize broad financial conditions and risk appetite.",
        "confidence_score": "0.88",
        "weight": "0.87",
        "lag_months": 0,
        "lag_notes": "Credit repricing often precedes softer activity and investment decisions.",
        "is_active": True,
    },
    {
        "code": "HY_OAS",
        "name": "High Yield OAS",
        "category": "credit",
        "description": "High-yield option-adjusted spread.",
        "frequency": "daily",
        "source": "Credit market data",
        "unit": "basis_points",
        "rationale": "HY spreads are a classic read on growth fears and financing stress.",
        "confidence_score": "0.90",
        "weight": "0.92",
        "lag_months": 0,
        "lag_notes": "Usually reacts quickly to cyclical deterioration or policy stress.",
        "is_active": True,
    },
]

# Derived drivers compress noisy raw indicators into reusable macro states.
DERIVED_DRIVERS = [
    {
        "code": "INFLATION_MOMENTUM",
        "name": "Inflation Momentum",
        "description": "Directional pressure in broad inflation prints.",
        "methodology": "Blend of CPI_YOY, CORE_CPI_YOY, and CORE_PCE_YOY trends.",
        "formula_expression": "weighted_change(CPI_YOY, CORE_CPI_YOY, CORE_PCE_YOY)",
        "indicator_codes": ["CPI_YOY", "CORE_CPI_YOY", "CORE_PCE_YOY"],
        "rationale": "Combines headline and core inflation to reduce single-series distortion.",
        "confidence_score": "0.94",
        "weight": "1.00",
        "lag_months": 1,
        "lag_notes": "Inflation momentum usually feeds policy expectations with a one-month reporting cadence.",
        "is_active": True,
    },
    {
        "code": "INFLATION_PERSISTENCE",
        "name": "Inflation Persistence",
        "description": "Stickiness of underlying inflation pressures.",
        "methodology": "Focus on CORE_CPI_YOY and CORE_PCE_YOY relative to prior disinflation pace.",
        "formula_expression": "persistence_score(CORE_CPI_YOY, CORE_PCE_YOY)",
        "indicator_codes": ["CORE_CPI_YOY", "CORE_PCE_YOY"],
        "rationale": "Persistent core inflation matters more than one-off commodity swings for policy.",
        "confidence_score": "0.92",
        "weight": "0.95",
        "lag_months": 2,
        "lag_notes": "Persistence is clearer across several prints rather than one release.",
        "is_active": True,
    },
    {
        "code": "LABOR_MARKET_TIGHTNESS",
        "name": "Labor Market Tightness",
        "description": "Balance between labor demand and available slack.",
        "methodology": "Use UNEMP_RATE inversely and reinforce with NFP_3M_AVG trend.",
        "formula_expression": "inverse(UNEMP_RATE) + trend(NFP_3M_AVG)",
        "indicator_codes": ["UNEMP_RATE", "NFP_3M_AVG"],
        "rationale": "Labor tightness often sustains wage and service inflation pressure.",
        "confidence_score": "0.90",
        "weight": "0.93",
        "lag_months": 1,
        "lag_notes": "Labor conditions are slower moving than market prices.",
        "is_active": True,
    },
    {
        "code": "GROWTH_MOMENTUM",
        "name": "Growth Momentum",
        "description": "Near-term activity momentum across the economy.",
        "methodology": "Blend ISM_MFG_PMI, ISM_SERVICES_PMI, and payroll trend.",
        "formula_expression": "blend(ISM_MFG_PMI, ISM_SERVICES_PMI, NFP_3M_AVG)",
        "indicator_codes": ["ISM_MFG_PMI", "ISM_SERVICES_PMI", "NFP_3M_AVG"],
        "rationale": "PMIs and payrolls together capture both surveys and realized demand strength.",
        "confidence_score": "0.89",
        "weight": "0.93",
        "lag_months": 0,
        "lag_notes": "Designed as a timely cycle read.",
        "is_active": True,
    },
    {
        "code": "POLICY_RESTRICTION",
        "name": "Policy Restriction",
        "description": "Tightness of monetary conditions implied by short rates versus inflation.",
        "methodology": "Compare UST2Y and UST10Y level with trailing core inflation direction.",
        "formula_expression": "restrictiveness(UST2Y, UST10Y, CORE_PCE_YOY)",
        "indicator_codes": ["UST2Y", "UST10Y", "CORE_PCE_YOY"],
        "rationale": "High nominal rates versus easing inflation usually imply tighter real conditions.",
        "confidence_score": "0.86",
        "weight": "0.90",
        "lag_months": 1,
        "lag_notes": "Monetary restriction impacts the real economy with long and variable lags.",
        "is_active": True,
    },
    {
        "code": "YIELD_CURVE_SLOPE",
        "name": "Yield Curve Slope",
        "description": "Term-structure signal from front-end versus long-end rates.",
        "methodology": "10Y minus 2Y slope classification.",
        "formula_expression": "UST10Y - UST2Y",
        "indicator_codes": ["UST10Y", "UST2Y"],
        "rationale": "Curve inversion has long been used as a recession-risk heuristic.",
        "confidence_score": "0.87",
        "weight": "0.92",
        "lag_months": 6,
        "lag_notes": "Curve signals often lead hard-landing risk by several quarters.",
        "is_active": True,
    },
    {
        "code": "REAL_RATE_PRESSURE",
        "name": "Real Rate Pressure",
        "description": "Burden from rates relative to inflation direction.",
        "methodology": "Approximate real-rate pressure from UST10Y less CORE_PCE_YOY.",
        "formula_expression": "UST10Y - CORE_PCE_YOY",
        "indicator_codes": ["UST10Y", "CORE_PCE_YOY"],
        "rationale": "Higher real rates tend to tighten equity multiples and interest-sensitive demand.",
        "confidence_score": "0.88",
        "weight": "0.90",
        "lag_months": 3,
        "lag_notes": "Transmission is faster in markets than in the real economy.",
        "is_active": True,
    },
    {
        "code": "CREDIT_STRESS",
        "name": "Credit Stress",
        "description": "Broad financing stress signaled by spread widening.",
        "methodology": "Blend IG_OAS and HY_OAS with extra weight on HY_OAS.",
        "formula_expression": "weighted_spread(IG_OAS, HY_OAS)",
        "indicator_codes": ["IG_OAS", "HY_OAS"],
        "rationale": "Credit spreads are a high-signal read on tightening financial conditions.",
        "confidence_score": "0.93",
        "weight": "0.98",
        "lag_months": 1,
        "lag_notes": "Spread moves can lead capex and employment deterioration.",
        "is_active": True,
    },
    {
        "code": "USD_LIQUIDITY_TIGHTNESS",
        "name": "USD Liquidity Tightness",
        "description": "Global liquidity pressure proxied by dollar strength and spreads.",
        "methodology": "Blend DXY with IG_OAS and HY_OAS direction.",
        "formula_expression": "liquidity_tightness(DXY, IG_OAS, HY_OAS)",
        "indicator_codes": ["DXY", "IG_OAS", "HY_OAS"],
        "rationale": "A stronger dollar plus wider spreads usually tightens global funding conditions.",
        "confidence_score": "0.85",
        "weight": "0.87",
        "lag_months": 1,
        "lag_notes": "Often shows up first in EM and risk-assets before hard data.",
        "is_active": True,
    },
    {
        "code": "COMMODITY_INFLATION_IMPULSE",
        "name": "Commodity Inflation Impulse",
        "description": "Upstream commodity pressure feeding inflation expectations.",
        "methodology": "Blend Brent direction with copper-gold cyclicality signal.",
        "formula_expression": "commodity_impulse(BRENT, COPPER_GOLD_RATIO)",
        "indicator_codes": ["BRENT", "COPPER_GOLD_RATIO"],
        "rationale": "Commodity moves often feed narrative shifts on inflation and growth together.",
        "confidence_score": "0.80",
        "weight": "0.78",
        "lag_months": 1,
        "lag_notes": "Pass-through varies and is less stable than core inflation measures.",
        "is_active": True,
    },
    {
        "code": "RECESSION_PROBABILITY_PROXY",
        "name": "Recession Probability Proxy",
        "description": "Composite heuristic for downturn risk.",
        "methodology": "Use curve inversion, rising unemployment, softer PMIs, and widening credit spreads.",
        "formula_expression": "composite(YIELD_CURVE_SLOPE, UNEMP_RATE, ISM_MFG_PMI, HY_OAS)",
        "indicator_codes": ["UST10Y", "UST2Y", "UNEMP_RATE", "ISM_MFG_PMI", "HY_OAS"],
        "rationale": "Recessions are usually multi-factor, so a composite is more robust than one trigger.",
        "confidence_score": "0.90",
        "weight": "1.00",
        "lag_months": 6,
        "lag_notes": "Designed as a medium-horizon warning signal.",
        "is_active": True,
    },
    {
        "code": "RISK_APPETITE",
        "name": "Risk Appetite",
        "description": "Market willingness to embrace cyclical and lower-quality exposure.",
        "methodology": "Infer from HY_OAS compression, copper-gold strength, and stable dollar conditions.",
        "formula_expression": "risk_appetite(HY_OAS, COPPER_GOLD_RATIO, DXY)",
        "indicator_codes": ["HY_OAS", "COPPER_GOLD_RATIO", "DXY"],
        "rationale": "Cross-asset signals often capture shifts in risk appetite before macro revisions.",
        "confidence_score": "0.82",
        "weight": "0.81",
        "lag_months": 0,
        "lag_notes": "Mostly coincident in markets rather than predictive in isolation.",
        "is_active": True,
    },
]

# Rules are grouped by theme so later refinement can swap out one block at a time.
CAUSAL_RULES = [
    # Inflation acceleration rules.
    {
        "code": "RULE_INF_01",
        "name": "Core inflation acceleration lifts policy restriction",
        "description": "Persistent core inflation usually forces a more restrictive policy stance.",
        "lead_indicator_code": "CORE_PCE_YOY",
        "derived_driver_code": "POLICY_RESTRICTION",
        "condition_expression": "CORE_PCE_YOY rising above recent trend",
        "effect_expression": "Increase POLICY_RESTRICTION",
        "rationale": "Central banks tend to lean tighter when preferred core inflation runs above target and trend.",
        "confidence_score": "0.94",
        "weight": "1.00",
        "lag_months": 1,
        "lag_notes": "Policy expectations usually adjust within one to two meetings.",
        "is_active": True,
    },
    {
        "code": "RULE_INF_02",
        "name": "Headline inflation spike lifts commodity inflation impulse",
        "description": "A sharp rise in headline inflation often reflects or reinforces commodity pressure.",
        "lead_indicator_code": "CPI_YOY",
        "derived_driver_code": "COMMODITY_INFLATION_IMPULSE",
        "condition_expression": "CPI_YOY reaccelerates after disinflation",
        "effect_expression": "Increase COMMODITY_INFLATION_IMPULSE",
        "rationale": "Energy and goods moves tend to show up quickly in headline inflation narratives.",
        "confidence_score": "0.76",
        "weight": "0.72",
        "lag_months": 0,
        "lag_notes": "More coincident than predictive.",
        "is_active": True,
    },
    {
        "code": "RULE_INF_03",
        "name": "Sticky core CPI raises inflation persistence",
        "description": "Higher-for-longer core inflation implies slower normalization.",
        "lead_indicator_code": "CORE_CPI_YOY",
        "derived_driver_code": "INFLATION_PERSISTENCE",
        "condition_expression": "CORE_CPI_YOY remains elevated for multiple releases",
        "effect_expression": "Increase INFLATION_PERSISTENCE",
        "rationale": "Multi-print stickiness is one of the cleanest persistence signals.",
        "confidence_score": "0.95",
        "weight": "0.98",
        "lag_months": 2,
        "lag_notes": "Persistence becomes clearer after several monthly observations.",
        "is_active": True,
    },
    {
        "code": "RULE_INF_04",
        "name": "Falling core PCE reduces real rate pressure if nominal yields lag",
        "description": "Disinflation can ease pressure if nominal yields do not rise further.",
        "lead_indicator_code": "CORE_PCE_YOY",
        "derived_driver_code": "REAL_RATE_PRESSURE",
        "condition_expression": "CORE_PCE_YOY falling faster than UST10Y",
        "effect_expression": "Decrease REAL_RATE_PRESSURE",
        "rationale": "Real-rate pressure only eases when nominal rates remain contained relative to inflation.",
        "confidence_score": "0.71",
        "weight": "0.65",
        "lag_months": 1,
        "lag_notes": "Can be offset by market repricing higher long rates.",
        "is_active": True,
    },
    {
        "code": "RULE_INF_05",
        "name": "Oil shock can reaccelerate inflation momentum",
        "description": "A crude spike often pushes broad inflation expectations higher.",
        "lead_indicator_code": "BRENT",
        "derived_driver_code": "INFLATION_MOMENTUM",
        "condition_expression": "BRENT rises sharply over a short window",
        "effect_expression": "Increase INFLATION_MOMENTUM",
        "rationale": "Oil shocks feed transport, energy, and inflation expectation channels.",
        "confidence_score": "0.79",
        "weight": "0.74",
        "lag_months": 1,
        "lag_notes": "Pass-through is faster to expectations than to sticky core inflation.",
        "is_active": True,
    },
    {
        "code": "RULE_INF_06",
        "name": "Dollar strength can soften imported inflation pressure",
        "description": "A stronger dollar tends to damp imported goods inflation over time.",
        "lead_indicator_code": "DXY",
        "derived_driver_code": "INFLATION_MOMENTUM",
        "condition_expression": "DXY strengthens materially while commodities are stable",
        "effect_expression": "Decrease INFLATION_MOMENTUM",
        "rationale": "FX appreciation can reduce imported price pressure with some lag.",
        "confidence_score": "0.67",
        "weight": "0.58",
        "lag_months": 3,
        "lag_notes": "Pass-through is partial and delayed.",
        "is_active": True,
    },
    # Labor and growth rules.
    {
        "code": "RULE_GRO_01",
        "name": "Lower unemployment raises labor tightness",
        "description": "Falling unemployment generally signals tighter labor conditions.",
        "lead_indicator_code": "UNEMP_RATE",
        "derived_driver_code": "LABOR_MARKET_TIGHTNESS",
        "condition_expression": "UNEMP_RATE falling below trailing average",
        "effect_expression": "Increase LABOR_MARKET_TIGHTNESS",
        "rationale": "Lower unemployment is a simple, accepted proxy for diminishing slack.",
        "confidence_score": "0.93",
        "weight": "0.95",
        "lag_months": 1,
        "lag_notes": "Labor market data tends to move gradually.",
        "is_active": True,
    },
    {
        "code": "RULE_GRO_02",
        "name": "Payroll cooling reduces growth momentum",
        "description": "A weaker payroll trend often flags softer aggregate demand.",
        "lead_indicator_code": "NFP_3M_AVG",
        "derived_driver_code": "GROWTH_MOMENTUM",
        "condition_expression": "NFP_3M_AVG falling toward stall speed",
        "effect_expression": "Decrease GROWTH_MOMENTUM",
        "rationale": "Broad hiring slowdowns usually accompany weaker growth momentum.",
        "confidence_score": "0.89",
        "weight": "0.90",
        "lag_months": 1,
        "lag_notes": "Payrolls can be revised, so trend emphasis matters.",
        "is_active": True,
    },
    {
        "code": "RULE_GRO_03",
        "name": "Manufacturing PMI above expansion lifts growth momentum",
        "description": "Expansionary manufacturing survey data supports better growth expectations.",
        "lead_indicator_code": "ISM_MFG_PMI",
        "derived_driver_code": "GROWTH_MOMENTUM",
        "condition_expression": "ISM_MFG_PMI sustainably above 50",
        "effect_expression": "Increase GROWTH_MOMENTUM",
        "rationale": "PMIs are timely and often inflect before harder industrial data.",
        "confidence_score": "0.86",
        "weight": "0.84",
        "lag_months": 0,
        "lag_notes": "Near-contemporaneous signal.",
        "is_active": True,
    },
    {
        "code": "RULE_GRO_04",
        "name": "Services PMI weakness lowers growth momentum",
        "description": "A softer services economy usually drags broader demand expectations lower.",
        "lead_indicator_code": "ISM_SERVICES_PMI",
        "derived_driver_code": "GROWTH_MOMENTUM",
        "condition_expression": "ISM_SERVICES_PMI falls below recent average or below 50",
        "effect_expression": "Decrease GROWTH_MOMENTUM",
        "rationale": "Services dominate modern developed-market activity and labor demand.",
        "confidence_score": "0.89",
        "weight": "0.90",
        "lag_months": 0,
        "lag_notes": "Survey deterioration can be early but also sentiment-sensitive.",
        "is_active": True,
    },
    {
        "code": "RULE_GRO_05",
        "name": "Copper-gold strength supports cyclical growth sentiment",
        "description": "A stronger copper-gold ratio often aligns with improving growth expectations.",
        "lead_indicator_code": "COPPER_GOLD_RATIO",
        "derived_driver_code": "GROWTH_MOMENTUM",
        "condition_expression": "COPPER_GOLD_RATIO rising persistently",
        "effect_expression": "Increase GROWTH_MOMENTUM",
        "rationale": "Industrial metals outperforming gold often indicates better cyclicality.",
        "confidence_score": "0.73",
        "weight": "0.68",
        "lag_months": 0,
        "lag_notes": "Best used as a market confirmation signal.",
        "is_active": True,
    },
    {
        "code": "RULE_GRO_06",
        "name": "Higher real rates weigh on growth momentum",
        "description": "Higher real rates usually damp rate-sensitive activity and risk-taking.",
        "lead_indicator_code": "UST10Y",
        "derived_driver_code": "GROWTH_MOMENTUM",
        "condition_expression": "UST10Y rises while core inflation is stable or falling",
        "effect_expression": "Decrease GROWTH_MOMENTUM",
        "rationale": "Real-rate tightening is one of the classic late-cycle brakes.",
        "confidence_score": "0.82",
        "weight": "0.79",
        "lag_months": 3,
        "lag_notes": "Transmission to activity is not immediate.",
        "is_active": True,
    },
    # Rates and policy rules.
    {
        "code": "RULE_POL_01",
        "name": "Front-end yield repricing lifts policy restriction",
        "description": "A rising 2Y yield typically signals tighter expected policy.",
        "lead_indicator_code": "UST2Y",
        "derived_driver_code": "POLICY_RESTRICTION",
        "condition_expression": "UST2Y rises sharply on macro repricing",
        "effect_expression": "Increase POLICY_RESTRICTION",
        "rationale": "The 2Y is among the cleanest market proxies for policy expectations.",
        "confidence_score": "0.95",
        "weight": "1.00",
        "lag_months": 0,
        "lag_notes": "Immediate market signal.",
        "is_active": True,
    },
    {
        "code": "RULE_POL_02",
        "name": "Curve inversion raises recession probability proxy",
        "description": "A deeply inverted curve historically correlates with later recession risk.",
        "lead_indicator_code": "UST2Y",
        "derived_driver_code": "RECESSION_PROBABILITY_PROXY",
        "condition_expression": "UST2Y above UST10Y for a sustained period",
        "effect_expression": "Increase RECESSION_PROBABILITY_PROXY",
        "rationale": "Curve inversion is a durable macro heuristic even if timing is uncertain.",
        "confidence_score": "0.91",
        "weight": "0.97",
        "lag_months": 6,
        "lag_notes": "Lead time is often several quarters.",
        "is_active": True,
    },
    {
        "code": "RULE_POL_03",
        "name": "Long-end yield breakout increases real rate pressure",
        "description": "Higher long yields mechanically tighten valuation and financing conditions.",
        "lead_indicator_code": "UST10Y",
        "derived_driver_code": "REAL_RATE_PRESSURE",
        "condition_expression": "UST10Y breaks materially above recent range",
        "effect_expression": "Increase REAL_RATE_PRESSURE",
        "rationale": "Discount-rate sensitivity is immediate in duration-heavy assets.",
        "confidence_score": "0.92",
        "weight": "0.95",
        "lag_months": 0,
        "lag_notes": "Market transmission is immediate.",
        "is_active": True,
    },
    {
        "code": "RULE_POL_04",
        "name": "Disinflation plus stable front-end reduces policy restriction",
        "description": "If inflation cools and front-end yields do not reprice higher, restriction eases.",
        "lead_indicator_code": "CORE_PCE_YOY",
        "derived_driver_code": "POLICY_RESTRICTION",
        "condition_expression": "CORE_PCE_YOY falling while UST2Y is flat to lower",
        "effect_expression": "Decrease POLICY_RESTRICTION",
        "rationale": "Easier inflation gives policymakers room to step back from peak restriction.",
        "confidence_score": "0.84",
        "weight": "0.85",
        "lag_months": 2,
        "lag_notes": "Depends on policy communication and growth backdrop.",
        "is_active": True,
    },
    {
        "code": "RULE_POL_05",
        "name": "Stronger labor market can extend restrictive policy",
        "description": "Resilient labor data may delay the easing cycle.",
        "lead_indicator_code": "UNEMP_RATE",
        "derived_driver_code": "POLICY_RESTRICTION",
        "condition_expression": "UNEMP_RATE remains unusually low while inflation is above target",
        "effect_expression": "Increase POLICY_RESTRICTION",
        "rationale": "Tight labor markets complicate the final leg of disinflation.",
        "confidence_score": "0.83",
        "weight": "0.80",
        "lag_months": 1,
        "lag_notes": "Often visible through policy commentary and market repricing.",
        "is_active": True,
    },
    {
        "code": "RULE_POL_06",
        "name": "Falling growth momentum steepens odds of later easing",
        "description": "Slower activity typically reduces the durability of restrictive policy.",
        "lead_indicator_code": "ISM_MFG_PMI",
        "derived_driver_code": "POLICY_RESTRICTION",
        "condition_expression": "ISM_MFG_PMI deeply contractionary alongside softer payrolls",
        "effect_expression": "Decrease POLICY_RESTRICTION",
        "rationale": "Material growth damage often precedes expectations of policy relief.",
        "confidence_score": "0.80",
        "weight": "0.78",
        "lag_months": 3,
        "lag_notes": "Market pricing often anticipates the actual policy response.",
        "is_active": True,
    },
    # Credit and liquidity rules.
    {
        "code": "RULE_CRD_01",
        "name": "High-yield spread widening raises credit stress",
        "description": "Wider HY spreads are a direct stress signal.",
        "lead_indicator_code": "HY_OAS",
        "derived_driver_code": "CREDIT_STRESS",
        "condition_expression": "HY_OAS widens materially over a short horizon",
        "effect_expression": "Increase CREDIT_STRESS",
        "rationale": "HY is typically the most cyclical and stress-sensitive credit segment.",
        "confidence_score": "0.97",
        "weight": "1.00",
        "lag_months": 0,
        "lag_notes": "Immediate financial-conditions signal.",
        "is_active": True,
    },
    {
        "code": "RULE_CRD_02",
        "name": "Investment-grade spread widening raises credit stress",
        "description": "IG spread widening signals broader tightening beyond speculative credit.",
        "lead_indicator_code": "IG_OAS",
        "derived_driver_code": "CREDIT_STRESS",
        "condition_expression": "IG_OAS widens persistently",
        "effect_expression": "Increase CREDIT_STRESS",
        "rationale": "Broader spread widening often indicates systemic rather than isolated stress.",
        "confidence_score": "0.90",
        "weight": "0.88",
        "lag_months": 0,
        "lag_notes": "Immediate market signal.",
        "is_active": True,
    },
    {
        "code": "RULE_CRD_03",
        "name": "Dollar strength raises USD liquidity tightness",
        "description": "A stronger dollar usually tightens global financial conditions.",
        "lead_indicator_code": "DXY",
        "derived_driver_code": "USD_LIQUIDITY_TIGHTNESS",
        "condition_expression": "DXY appreciating rapidly on risk-off or rate differentials",
        "effect_expression": "Increase USD_LIQUIDITY_TIGHTNESS",
        "rationale": "Dollar strength can strain external funding, especially outside the US.",
        "confidence_score": "0.88",
        "weight": "0.90",
        "lag_months": 0,
        "lag_notes": "Transmission into liquid markets is fast.",
        "is_active": True,
    },
    {
        "code": "RULE_CRD_04",
        "name": "Combined spread widening and stronger dollar raise recession risk",
        "description": "Tighter global funding conditions often precede weaker activity.",
        "lead_indicator_code": "HY_OAS",
        "derived_driver_code": "RECESSION_PROBABILITY_PROXY",
        "condition_expression": "HY_OAS widening alongside firmer DXY",
        "effect_expression": "Increase RECESSION_PROBABILITY_PROXY",
        "rationale": "Financial tightening compounds slower domestic demand and funding stress.",
        "confidence_score": "0.84",
        "weight": "0.86",
        "lag_months": 3,
        "lag_notes": "Recession signaling horizon is medium term.",
        "is_active": True,
    },
    {
        "code": "RULE_CRD_05",
        "name": "Spread compression improves risk appetite",
        "description": "Tighter spreads are a straightforward read on improving risk appetite.",
        "lead_indicator_code": "HY_OAS",
        "derived_driver_code": "RISK_APPETITE",
        "condition_expression": "HY_OAS tightening while defaults remain contained",
        "effect_expression": "Increase RISK_APPETITE",
        "rationale": "Investors usually demand less compensation when cyclical fears fade.",
        "confidence_score": "0.85",
        "weight": "0.84",
        "lag_months": 0,
        "lag_notes": "Mostly coincident with market mood.",
        "is_active": True,
    },
    {
        "code": "RULE_CRD_06",
        "name": "Credit stress drags growth momentum",
        "description": "Wider spreads eventually flow into slower borrowing and investment.",
        "lead_indicator_code": "HY_OAS",
        "derived_driver_code": "GROWTH_MOMENTUM",
        "condition_expression": "HY_OAS and IG_OAS both widening",
        "effect_expression": "Decrease GROWTH_MOMENTUM",
        "rationale": "Tighter credit conditions usually weaken capex, hiring, and demand.",
        "confidence_score": "0.88",
        "weight": "0.91",
        "lag_months": 2,
        "lag_notes": "Real-economy pass-through is slower than market repricing.",
        "is_active": True,
    },
    # Cross-asset confirmation rules.
    {
        "code": "RULE_XAS_01",
        "name": "Copper-gold strength improves risk appetite",
        "description": "A stronger cyclical metals signal often aligns with better risk tone.",
        "lead_indicator_code": "COPPER_GOLD_RATIO",
        "derived_driver_code": "RISK_APPETITE",
        "condition_expression": "COPPER_GOLD_RATIO breaks above trend",
        "effect_expression": "Increase RISK_APPETITE",
        "rationale": "Cyclical leadership over defensives is a classic market heuristic.",
        "confidence_score": "0.78",
        "weight": "0.73",
        "lag_months": 0,
        "lag_notes": "Confirmation signal rather than standalone driver.",
        "is_active": True,
    },
    {
        "code": "RULE_XAS_02",
        "name": "Oil spike with strong PMIs supports reflationary growth",
        "description": "Higher oil alongside solid PMIs often reads as reflation instead of pure shock.",
        "lead_indicator_code": "BRENT",
        "derived_driver_code": "GROWTH_MOMENTUM",
        "condition_expression": "BRENT rising while PMIs stay expansionary",
        "effect_expression": "Increase GROWTH_MOMENTUM",
        "rationale": "Commodity strength can reflect firm demand if activity data is also healthy.",
        "confidence_score": "0.69",
        "weight": "0.63",
        "lag_months": 0,
        "lag_notes": "Context-dependent because supply shocks can invert the interpretation.",
        "is_active": True,
    },
    {
        "code": "RULE_XAS_03",
        "name": "Oil spike with weak PMIs raises recession probability proxy",
        "description": "An energy shock into slowing growth can tip conditions toward stagflationary slowdown.",
        "lead_indicator_code": "BRENT",
        "derived_driver_code": "RECESSION_PROBABILITY_PROXY",
        "condition_expression": "BRENT rising while ISM_MFG_PMI and ISM_SERVICES_PMI are weakening",
        "effect_expression": "Increase RECESSION_PROBABILITY_PROXY",
        "rationale": "Negative supply shocks are more dangerous when demand is already softening.",
        "confidence_score": "0.77",
        "weight": "0.75",
        "lag_months": 2,
        "lag_notes": "Growth damage emerges after the immediate inflation shock.",
        "is_active": True,
    },
    {
        "code": "RULE_XAS_04",
        "name": "Lower long yields can relieve real rate pressure",
        "description": "A rally in long bonds often eases duration-sensitive stress.",
        "lead_indicator_code": "UST10Y",
        "derived_driver_code": "REAL_RATE_PRESSURE",
        "condition_expression": "UST10Y falls decisively while inflation is stable",
        "effect_expression": "Decrease REAL_RATE_PRESSURE",
        "rationale": "Lower discount rates tend to support valuations and financing conditions.",
        "confidence_score": "0.88",
        "weight": "0.86",
        "lag_months": 0,
        "lag_notes": "Immediate market effect.",
        "is_active": True,
    },
    {
        "code": "RULE_XAS_05",
        "name": "Dollar weakness can improve risk appetite",
        "description": "A softer dollar often eases external funding pressure and supports cyclicals.",
        "lead_indicator_code": "DXY",
        "derived_driver_code": "RISK_APPETITE",
        "condition_expression": "DXY trending lower without a growth scare",
        "effect_expression": "Increase RISK_APPETITE",
        "rationale": "Dollar weakness often broadens global liquidity and improves risk tone.",
        "confidence_score": "0.74",
        "weight": "0.69",
        "lag_months": 1,
        "lag_notes": "Often clearer in EM and commodities first.",
        "is_active": True,
    },
    {
        "code": "RULE_XAS_06",
        "name": "Long-end selloff with wider spreads tightens liquidity",
        "description": "Simultaneous higher yields and wider spreads usually imply broad tightening.",
        "lead_indicator_code": "UST10Y",
        "derived_driver_code": "USD_LIQUIDITY_TIGHTNESS",
        "condition_expression": "UST10Y rising while IG_OAS and HY_OAS widen",
        "effect_expression": "Increase USD_LIQUIDITY_TIGHTNESS",
        "rationale": "Higher rates and wider spreads are the essence of tighter market-based conditions.",
        "confidence_score": "0.87",
        "weight": "0.90",
        "lag_months": 0,
        "lag_notes": "Immediate cross-asset tightening signal.",
        "is_active": True,
    },
    # Composite regime-preparation rules.
    {
        "code": "RULE_CMP_01",
        "name": "Soft inflation and solid PMIs support Goldilocks conditions",
        "description": "Cooling inflation without a growth break is the classic benign setup.",
        "lead_indicator_code": "CORE_PCE_YOY",
        "derived_driver_code": "GROWTH_MOMENTUM",
        "condition_expression": "CORE_PCE_YOY falling while ISM_SERVICES_PMI stays expansionary",
        "effect_expression": "Maintain or slightly increase GROWTH_MOMENTUM",
        "rationale": "This combination historically underpins the Goldilocks narrative.",
        "confidence_score": "0.82",
        "weight": "0.79",
        "lag_months": 1,
        "lag_notes": "Needs confirmation across multiple releases.",
        "is_active": True,
    },
    {
        "code": "RULE_CMP_02",
        "name": "Low unemployment plus sticky inflation supports overheating risk",
        "description": "Tight labor and sticky prices usually describe a late-cycle overheating setup.",
        "lead_indicator_code": "UNEMP_RATE",
        "derived_driver_code": "INFLATION_PERSISTENCE",
        "condition_expression": "UNEMP_RATE low while CORE_CPI_YOY remains elevated",
        "effect_expression": "Increase INFLATION_PERSISTENCE",
        "rationale": "Labor-market resilience can keep services inflation sticky.",
        "confidence_score": "0.86",
        "weight": "0.84",
        "lag_months": 2,
        "lag_notes": "Lag reflects slower persistence confirmation.",
        "is_active": True,
    },
    {
        "code": "RULE_CMP_03",
        "name": "Soft PMIs and wider spreads raise recession probability proxy",
        "description": "Weak surveys with tighter credit meaningfully increase downturn odds.",
        "lead_indicator_code": "ISM_MFG_PMI",
        "derived_driver_code": "RECESSION_PROBABILITY_PROXY",
        "condition_expression": "ISM_MFG_PMI contractionary while HY_OAS widens",
        "effect_expression": "Increase RECESSION_PROBABILITY_PROXY",
        "rationale": "Survey weakness becomes more actionable when financial conditions also tighten.",
        "confidence_score": "0.91",
        "weight": "0.96",
        "lag_months": 3,
        "lag_notes": "The combination is more informative than either signal alone.",
        "is_active": True,
    },
    {
        "code": "RULE_CMP_04",
        "name": "Commodity impulse can offset weak manufacturing temporarily",
        "description": "Commodity-led reflation can mask manufacturing softness for a time.",
        "lead_indicator_code": "BRENT",
        "derived_driver_code": "INFLATION_MOMENTUM",
        "condition_expression": "BRENT and COPPER_GOLD_RATIO rising while ISM_MFG_PMI is soft",
        "effect_expression": "Increase INFLATION_MOMENTUM despite weaker manufacturing",
        "rationale": "Supply-side and commodity channels can hold inflation up even as production softens.",
        "confidence_score": "0.72",
        "weight": "0.67",
        "lag_months": 1,
        "lag_notes": "Useful mainly for stagflation framing.",
        "is_active": True,
    },
    {
        "code": "RULE_CMP_05",
        "name": "Falling unemployment and tighter spreads support risk appetite",
        "description": "Healthy labor plus benign credit usually aligns with better risk tone.",
        "lead_indicator_code": "UNEMP_RATE",
        "derived_driver_code": "RISK_APPETITE",
        "condition_expression": "UNEMP_RATE stable to lower while HY_OAS tightens",
        "effect_expression": "Increase RISK_APPETITE",
        "rationale": "Macro stability and easier credit encourage cyclical positioning.",
        "confidence_score": "0.80",
        "weight": "0.78",
        "lag_months": 1,
        "lag_notes": "Useful as a broad cross-check on benign conditions.",
        "is_active": True,
    },
    {
        "code": "RULE_CMP_06",
        "name": "Rising unemployment with falling yields may signal defensive disinflation",
        "description": "A weakening labor market plus lower yields often points to slowdown rather than reflation.",
        "lead_indicator_code": "UNEMP_RATE",
        "derived_driver_code": "RECESSION_PROBABILITY_PROXY",
        "condition_expression": "UNEMP_RATE rising while UST10Y falls and PMIs weaken",
        "effect_expression": "Increase RECESSION_PROBABILITY_PROXY",
        "rationale": "Bond rallies into labor weakness usually reflect softer growth expectations.",
        "confidence_score": "0.83",
        "weight": "0.82",
        "lag_months": 2,
        "lag_notes": "Typically emerges through an evolving slowdown sequence.",
        "is_active": True,
    },
]

DIVERGENCE_PATTERNS = [
    {
        "code": "DIV_01",
        "name": "Sticky Core, Falling Headline",
        "description": "Headline inflation cools while core remains stubbornly elevated.",
        "indicator_code": "CORE_CPI_YOY",
        "detection_expression": "CPI_YOY falling while CORE_CPI_YOY remains above trend",
        "severity_level": "medium",
        "rationale": "Often signals commodity relief without real progress in underlying services inflation.",
        "confidence_score": "0.91",
        "weight": "0.92",
        "lag_months": 1,
        "lag_notes": "Useful for separating headline relief from core stickiness.",
        "is_active": True,
    },
    {
        "code": "DIV_02",
        "name": "Strong Payrolls, Rising Unemployment",
        "description": "Payroll growth appears solid while unemployment rises.",
        "indicator_code": "NFP_3M_AVG",
        "detection_expression": "NFP_3M_AVG stable but UNEMP_RATE drifting higher",
        "severity_level": "medium",
        "rationale": "Can flag labor-market normalization beneath seemingly strong headline jobs data.",
        "confidence_score": "0.73",
        "weight": "0.70",
        "lag_months": 1,
        "lag_notes": "May reflect participation or household-survey shifts.",
        "is_active": True,
    },
    {
        "code": "DIV_03",
        "name": "Soft Manufacturing, Firm Services",
        "description": "Industrial weakness coexists with resilient domestic services demand.",
        "indicator_code": "ISM_MFG_PMI",
        "detection_expression": "ISM_MFG_PMI below 50 while ISM_SERVICES_PMI remains above 50",
        "severity_level": "low",
        "rationale": "This has been a common late-cycle split in modern service-heavy economies.",
        "confidence_score": "0.84",
        "weight": "0.78",
        "lag_months": 0,
        "lag_notes": "Usually a cycle-shape clue rather than a crisis signal.",
        "is_active": True,
    },
    {
        "code": "DIV_04",
        "name": "Rising Yields, Weak PMIs",
        "description": "Rates sell off even as survey growth data softens.",
        "indicator_code": "UST10Y",
        "detection_expression": "UST10Y rising while ISM_MFG_PMI and ISM_SERVICES_PMI weaken",
        "severity_level": "high",
        "rationale": "Often indicates policy or term-premium tightening into a fragile growth backdrop.",
        "confidence_score": "0.88",
        "weight": "0.93",
        "lag_months": 1,
        "lag_notes": "Can become a sharp tightening episode if persistent.",
        "is_active": True,
    },
    {
        "code": "DIV_05",
        "name": "Dollar Strength, Tight Credit",
        "description": "Stronger dollar is accompanied by wider spreads.",
        "indicator_code": "DXY",
        "detection_expression": "DXY rising alongside IG_OAS and HY_OAS widening",
        "severity_level": "high",
        "rationale": "This combination is a classic sign of global liquidity stress.",
        "confidence_score": "0.92",
        "weight": "0.96",
        "lag_months": 0,
        "lag_notes": "Often shows up before harder activity data.",
        "is_active": True,
    },
    {
        "code": "DIV_06",
        "name": "Oil Up, Growth Down",
        "description": "Energy prices rise while activity signals soften.",
        "indicator_code": "BRENT",
        "detection_expression": "BRENT rising while ISM_MFG_PMI weakens and NFP_3M_AVG slows",
        "severity_level": "high",
        "rationale": "A negative supply shock into softer demand is a classic stagflation pattern.",
        "confidence_score": "0.86",
        "weight": "0.90",
        "lag_months": 1,
        "lag_notes": "Often escalates inflation fears before growth damage is fully visible.",
        "is_active": True,
    },
    {
        "code": "DIV_07",
        "name": "Tight Labor, Falling PMIs",
        "description": "Labor data stays hot while surveys cool.",
        "indicator_code": "UNEMP_RATE",
        "detection_expression": "UNEMP_RATE low while ISM_MFG_PMI declines",
        "severity_level": "medium",
        "rationale": "Suggests the labor market is lagging a broader activity slowdown.",
        "confidence_score": "0.82",
        "weight": "0.81",
        "lag_months": 2,
        "lag_notes": "Labor often turns after surveys do.",
        "is_active": True,
    },
    {
        "code": "DIV_08",
        "name": "Yield Curve Inversion, Tight Spreads",
        "description": "Curve signals caution while credit markets stay complacent.",
        "indicator_code": "UST2Y",
        "detection_expression": "UST2Y above UST10Y while HY_OAS remains unusually tight",
        "severity_level": "medium",
        "rationale": "Markets sometimes delay pricing growth risk even after rates warn.",
        "confidence_score": "0.79",
        "weight": "0.76",
        "lag_months": 3,
        "lag_notes": "Useful as an early warning of later credit repricing.",
        "is_active": True,
    },
    {
        "code": "DIV_09",
        "name": "Falling Inflation, Rising Long Yields",
        "description": "Disinflation continues but term yields rise anyway.",
        "indicator_code": "CORE_PCE_YOY",
        "detection_expression": "CORE_PCE_YOY falling while UST10Y rises",
        "severity_level": "medium",
        "rationale": "May reflect term-premium or fiscal-supply pressure rather than growth strength.",
        "confidence_score": "0.77",
        "weight": "0.74",
        "lag_months": 0,
        "lag_notes": "Important for distinguishing rate-driven tightening from inflation-driven tightening.",
        "is_active": True,
    },
    {
        "code": "DIV_10",
        "name": "Copper Weak, Oil Strong",
        "description": "Industrial cyclicality weakens while energy strengthens.",
        "indicator_code": "COPPER_GOLD_RATIO",
        "detection_expression": "COPPER_GOLD_RATIO falling while BRENT rises",
        "severity_level": "high",
        "rationale": "Often points to supply-driven inflation rather than healthy global demand.",
        "confidence_score": "0.81",
        "weight": "0.83",
        "lag_months": 1,
        "lag_notes": "Useful as a stagflation warning pattern.",
        "is_active": True,
    },
    {
        "code": "DIV_11",
        "name": "Falling Yields, Strong Dollar",
        "description": "Bond rally occurs alongside dollar strength.",
        "indicator_code": "UST10Y",
        "detection_expression": "UST10Y falling while DXY rises",
        "severity_level": "medium",
        "rationale": "This can indicate defensive growth fears rather than benign easing.",
        "confidence_score": "0.75",
        "weight": "0.73",
        "lag_months": 0,
        "lag_notes": "Cross-asset context matters heavily.",
        "is_active": True,
    },
    {
        "code": "DIV_12",
        "name": "Core Inflation High, Credit Tight",
        "description": "Sticky inflation is colliding with worsening financing conditions.",
        "indicator_code": "CORE_PCE_YOY",
        "detection_expression": "CORE_PCE_YOY elevated while HY_OAS widens",
        "severity_level": "high",
        "rationale": "This is one of the more dangerous late-cycle combinations for policy and risk assets.",
        "confidence_score": "0.90",
        "weight": "0.95",
        "lag_months": 1,
        "lag_notes": "Useful for escalating stagflation or hard-landing watchlists.",
        "is_active": True,
    },
]

REGIMES = [
    {
        "code": "REG_GOLDILOCKS",
        "name": "Goldilocks Expansion",
        "regime_type": "benign_growth",
        "description": "Cooling inflation with still-positive growth and contained financial stress.",
        "primary_indicator_code": "CORE_PCE_YOY",
        "rationale": "This regime reflects the widely used soft-landing or Goldilocks framing.",
        "confidence_score": "0.84",
        "weight": "0.88",
        "lag_months": 1,
        "lag_notes": "Usually requires several releases to confirm.",
        "is_active": True,
    },
    {
        "code": "REG_REFLATION",
        "name": "Reflation",
        "regime_type": "growth_reacceleration",
        "description": "Growth improves alongside firmer yields and commodity support, but without acute stress.",
        "primary_indicator_code": "ISM_MFG_PMI",
        "rationale": "Reflation is a standard market regime when activity reaccelerates and cyclicals lead.",
        "confidence_score": "0.82",
        "weight": "0.85",
        "lag_months": 1,
        "lag_notes": "Often confirmed by PMIs and commodity-sensitive assets.",
        "is_active": True,
    },
    {
        "code": "REG_STAGFLATION",
        "name": "Stagflation",
        "regime_type": "inflationary_slowdown",
        "description": "Inflation remains problematic while growth momentum deteriorates.",
        "primary_indicator_code": "BRENT",
        "rationale": "The combination of sticky inflation and slowing growth is a classic stagflation setup.",
        "confidence_score": "0.90",
        "weight": "0.98",
        "lag_months": 1,
        "lag_notes": "Often emerges through supply shocks or persistent services inflation.",
        "is_active": True,
    },
    {
        "code": "REG_DISINFLATION_SLOWDOWN",
        "name": "Disinflationary Slowdown",
        "regime_type": "slowdown",
        "description": "Inflation cools but demand and labor conditions soften as policy bites.",
        "primary_indicator_code": "UNEMP_RATE",
        "rationale": "This is the classic late-tightening regime before either stabilization or recession.",
        "confidence_score": "0.88",
        "weight": "0.93",
        "lag_months": 2,
        "lag_notes": "Often visible after a prolonged restrictive policy phase.",
        "is_active": True,
    },
    {
        "code": "REG_HARD_LANDING",
        "name": "Hard Landing",
        "regime_type": "recession",
        "description": "Growth contracts materially, labor weakens, and credit stress intensifies.",
        "primary_indicator_code": "HY_OAS",
        "rationale": "A hard landing regime is defined by coincident macro deterioration and financial tightening.",
        "confidence_score": "0.92",
        "weight": "1.00",
        "lag_months": 3,
        "lag_notes": "Usually confirmed only after several indicators align.",
        "is_active": True,
    },
    {
        "code": "REG_OVERHEATING",
        "name": "Late-Cycle Overheating",
        "regime_type": "overheating",
        "description": "Labor remains tight, inflation stays sticky, and policy remains or becomes restrictive.",
        "primary_indicator_code": "UNEMP_RATE",
        "rationale": "This regime captures the widely accepted late-cycle overheating narrative.",
        "confidence_score": "0.86",
        "weight": "0.89",
        "lag_months": 2,
        "lag_notes": "Needs confirmation from both labor and core inflation persistence.",
        "is_active": True,
    },
]

